name: EPIC
description: File a new EPIC.
title: "[EPIC] "
labels: ["epic"]
type: EPIC
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this epic, you wannabe PM you...
  - type: textarea
    id: epic-description
    attributes:
      label: What do you want to see in Sprocket?
      description: "..."
      placeholder: "Come on now..."
    validations:
      required: true
